### ISSUE TITLE
Når jeg bruger templatet på en kampagne er mange felter væk

### ISSUE THREAD

**Issue by lsolesen** [mikkel-tschentscher/responsive-ecommerce-email-template#2]
Jeg har fulgt guiden ret grundigt. Når jeg vælger templatet, så er der ikke nogen edit felter fremme:

![skaermbillede 2017-04-01 kl 20 04 37](https://cloud.githubusercontent.com/assets/148026/24581173/a919370e-1716-11e7-8a97-42e3df22ed0b.png)

Jeg er ret ferm til HTML, Smarty, Mailchimp mv., så tror ikke jeg har lavet en fejl, men måske har Mailchimp ændret sig?

**Comment by lsolesen** [comment]
@mikkeltschentscher Det gør bl.a. at jeg ikke engang kan komme ind i noget HTML-view på Mailchimp.

**Comment by mikkeltschentscher** [comment]
1. Har du taget MailChimp versionen? Eller straight-HTML versionen?
2. Dét screenshot siger ikke meget. Kan du tage et full-screen så jeg kan se - hvor - i MailChimp du er?

3. .. Jeg har lige testet med en ny konto, og et nyt template. Alt spiller.

**Comment by lsolesen** [comment]
1. Jeg har valgt email-template-mailchimp.html og uploadet den. Det ser nogenlunde rigtigt ud, når jeg kigger på selve templatet, men de redigerbare felter er væk, når jeg står på "Design"-siden under oprettelsen af en ny kampagne.

2. Jeg er på Design-siden under oprettelsen af en ny kampagne "https://us2.admin.mailchimp.com/campaigns/wizard/neapolitan"

3. Det lyder godt. Kan problemet være, at kontoen ikke er en betalingskonto?

**Comment by lsolesen** [comment]
Måske kan det være fordi jeg har misforstået, hvordan det virker? Der er som default kun et felt fremme, hvor man kan klikke +. Synes det var vist lidt anderledes i videoen, men ser ud til, at jeg kan få det til at spille :) Prøver i hvert fald.

**Comment by mikkeltschentscher** [comment]
Cool! Ellers siger du bare til :-)
